### <center>**CONFIGURING LIBRARY IMPORTS📚**</center>

In [2]:
# Managing Data.
import pandas as pd
import numpy as np
import re
# -----------------------------------------------------------------------

# Evaluating the distribution of the relationship between variables.
import scipy.stats as stats
from scipy.stats import ttest_ind, norm, chi2_contingency, f_oneway
from scipy.stats import shapiro, kstest, poisson, chisquare, expon

# -----------------------------------------------------------------------

# Imputing nulls using advanced statistical methods.
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.experimental import enable_iterative_imputer
from sklearn.linear_model import LinearRegression

# -----------------------------------------------------------------------

# Visualisation libraries.
import seaborn as sns
import matplotlib.pyplot as plt

# -----------------------------------------------------------------------

# Managing warnings.
import warnings
warnings.filterwarnings("ignore")

# -----------------------------------------------------------------------

# Configuration: Checking the setting of the display to its maximum capacity to better show the dataframe.
pd.set_option('display.max_rows', None)  # Cambia el número máximo de filas mostradas
pd.set_option('display.max_columns', None)  # Cambia el número máximo de columnas mostradas para poder visualizar todas las columnas del DF
pd.set_option('display.width', None)  # Cambia el ancho máximo de la pantalla

### <center>**CSV DOCUMENT READING📂**</center>

In [3]:
# Opening/Reading the csv document as a DataFrame to start the process of exploration and analysis of the data.
df_onlinefoods = pd.read_csv("onlinefoods.csv")

### <center>**🔎EXPLORATORY DATA ANALYSIS (EDA)🔍**</center>
### <center>**PANDAS METHODS🐼**</center>

In [4]:
# Displaying the first 5 rows of the dataset (default is 5 rows).
df_onlinefoods.head()

Age  Gender Marital Status Occupation  Monthly Income  \
0   20  Female         Single    Student       No Income   
1   24  Female         Single    Student  Below Rs.10000   
2   22    Male         Single    Student  Below Rs.10000   
3   22  Female         Single    Student       No Income   
4   22    Male         Single    Student  Below Rs.10000   

  Educational Qualifications  Family size  latitude  longitude  Pin code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   

  Output   Feedback Unnamed: 12  
0    Yes   Positive         Yes  
1    Yes   Positive         Yes  
2    Yes  Negative          Yes  
3    Yes   Positive         Yes  
4    Yes   Positive         Yes

In [5]:
# Displaying the last 5 rows of the dataset (default is 5 rows).
df_onlinefoods.tail()

Age  Gender Marital Status Occupation  Monthly Income  \
383   23  Female         Single    Student       No Income   
384   23  Female         Single    Student       No Income   
385   22  Female         Single    Student       No Income   
386   23    Male         Single    Student  Below Rs.10000   
387   23    Male         Single    Student       No Income   

    Educational Qualifications  Family size  latitude  longitude  Pin code  \
383              Post Graduate            2   12.9766    77.5993    560001   
384              Post Graduate            4   12.9854    77.7081    560048   
385              Post Graduate            5   12.9850    77.5533    560010   
386              Post Graduate            2   12.9770    77.5773    560009   
387              Post Graduate            5   12.8988    77.5764    560078   

    Output  Feedback Unnamed: 12  
383    Yes  Positive         Yes  
384    Yes  Positive         Yes  
385    Yes  Positive         Yes  
386    Yes  Positive         Yes  
387    Yes  Positive         Yes

In [6]:
# Displaying a summary of the dataset, including data types, non-null counts, and memory usage.
df_onlinefoods.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 388 entries, 0 to 387
Data columns (total 13 columns):
 #   Column                      Non-Null Count  Dtype  
---  ------                      --------------  -----  
 0   Age                         388 non-null    int64  
 1   Gender                      388 non-null    object 
 2   Marital Status              388 non-null    object 
 3   Occupation                  388 non-null    object 
 4   Monthly Income              388 non-null    object 
 5   Educational Qualifications  388 non-null    object 
 6   Family size                 388 non-null    int64  
 7   latitude                    388 non-null    float64
 8   longitude                   388 non-null    float64
 9   Pin code                    388 non-null    int64  
 10  Output                      388 non-null    object 
 11  Feedback                    388 non-null    object 
 12  Unnamed: 12                 388 non-null    object 
dtypes: float64(2), int64(3), object(8)


In [7]:
# Printing a random sample of 5 entries to check the information displayed in each column.
df_onlinefoods.sample(5)

Age Gender Marital Status Occupation Monthly Income  \
256   23   Male         Single    Student      No Income   
190   24   Male         Single    Student      No Income   
340   23   Male         Single    Student      No Income   
87    25   Male         Single    Student      No Income   
107   25   Male         Single    Student      No Income   

    Educational Qualifications  Family size  latitude  longitude  Pin code  \
256              Post Graduate            2   12.9770    77.5773    560009   
190              Post Graduate            3   13.0487    77.5923    560024   
340                   Graduate            3   13.0223    77.7132    560049   
87                    Graduate            1   12.9770    77.5773    560009   
107              Post Graduate            1   12.9343    77.6044    560029   

    Output   Feedback Unnamed: 12  
256     No  Negative           No  
190     No  Negative           No  
340    Yes   Positive         Yes  
87     Yes   Positive         Yes  
107    Yes   Positive         Yes

In [8]:
# Checking the number of rows and columns in several ways:

# Method 1: len(df) gives the number of rows, len(df.columns) gives the number of columns
print(len(df_onlinefoods))
print(len(df_onlinefoods.columns))

# Method 2: .shape attribute to display the number of rows and columns separately
print(f"Number of rows: {df_onlinefoods.shape[0]}\nNumber of columns: {df_onlinefoods.shape[1]}")

# Method 3: .shape attribute provides a tuple (rows, columns)
df_onlinefoods.shape

388
13
Number of rows: 388
Number of columns: 13


(388, 13)

In [9]:
# Printing the name of the columns separately.
df_onlinefoods.columns

Index(['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', 'Unnamed: 12'],
      dtype='object')

In [10]:
# Displaying descriptive statistics for numerical columns in the dataset.
df_onlinefoods.describe()

Age  Family size    latitude   longitude       Pin code
count  388.000000   388.000000  388.000000  388.000000     388.000000
mean    24.628866     3.280928   12.972058   77.600160  560040.113402
std      2.975593     1.351025    0.044489    0.051354      31.399609
min     18.000000     1.000000   12.865200   77.484200  560001.000000
25%     23.000000     2.000000   12.936900   77.565275  560010.750000
50%     24.000000     3.000000   12.977000   77.592100  560033.500000
75%     26.000000     4.000000   12.997025   77.630900  560068.000000
max     33.000000     6.000000   13.102000   77.758200  560109.000000

In [11]:
# Displaying descriptive statistics for object columns in the dataset.
df_onlinefoods.describe(include = "object").T

count unique        top freq
Gender                       388      2       Male  222
Marital Status               388      3     Single  268
Occupation                   388      4    Student  207
Monthly Income               388      5  No Income  187
Educational Qualifications   388      5   Graduate  177
Output                       388      2        Yes  301
Feedback                     388      2   Positive  317
Unnamed: 12                  388      2        Yes  301

In [12]:
# Printing the names of the numeric columns.
numeric_columns = df_onlinefoods.select_dtypes(include = np.number).columns
numeric_columns

Index(['Age', 'Family size', 'latitude', 'longitude', 'Pin code'], dtype='object')

In [13]:
# Printing the names of the object columns.
string_columns = df_onlinefoods.select_dtypes(include = "object").columns
string_columns

Index(['Gender', 'Marital Status', 'Occupation', 'Monthly Income',
       'Educational Qualifications', 'Output', 'Feedback', 'Unnamed: 12'],
      dtype='object')

### <center>**VALUES**</center>

Printing out the counts of unique values in a Series, sorted in descending order of each column composing the Dataset to know both the unique values and their frequency of occurrence.

In [14]:
df_onlinefoods['Age'].value_counts()

Age
23    73
22    57
25    52
24    50
26    35
21    23
27    21
32    16
28    15
29    14
20     9
30     9
31     8
19     4
18     1
33     1
Name: count, dtype: int64

In [15]:
df_onlinefoods['Gender'].value_counts()

Gender
Male      222
Female    166
Name: count, dtype: int64

In [16]:
df_onlinefoods['Marital Status'].value_counts()

Marital Status
Single               268
Married              108
Prefer not to say     12
Name: count, dtype: int64

In [17]:
df_onlinefoods['Occupation'].value_counts()

Occupation
Student           207
Employee          118
Self Employeed     54
House wife          9
Name: count, dtype: int64

In [18]:
df_onlinefoods['Monthly Income'].value_counts()

Monthly Income
No Income          187
25001 to 50000      69
More than 50000     62
10001 to 25000      45
Below Rs.10000      25
Name: count, dtype: int64

In [19]:
df_onlinefoods['Educational Qualifications'].value_counts()

Educational Qualifications
Graduate         177
Post Graduate    174
Ph.D              23
School            12
Uneducated         2
Name: count, dtype: int64

In [20]:
df_onlinefoods['Family size'].value_counts()

Family size
3    117
2    101
4     63
5     54
6     29
1     24
Name: count, dtype: int64

In [21]:
df_onlinefoods['latitude'].value_counts()

latitude
12.9770    36
12.9783    16
12.9850    14
12.8845    12
12.9261    11
12.9369    11
12.9048     9
12.9706     9
12.9343     8
13.0487     8
12.9766     8
12.9698     8
13.0206     8
13.0103     8
13.0626     7
12.9570     7
12.9337     7
13.0158     7
13.0019     7
12.9980     6
12.9551     6
12.9306     6
12.9561     6
12.9635     6
12.9925     6
12.9217     6
12.9820     6
12.9757     5
13.0641     5
12.9889     5
13.0138     5
12.9442     5
12.9299     5
12.9438     5
12.9828     5
12.8988     5
12.9149     4
12.8893     4
12.9854     4
13.0140     4
13.0012     4
12.9579     4
13.0734     4
12.9967     4
12.9847     4
12.9859     4
13.0289     3
12.9037     3
12.9662     3
13.0166     3
12.9335     2
13.1020     2
12.8834     2
12.9105     2
12.9515     2
13.0067     2
12.9119     2
13.0223     2
13.0503     2
13.0298     2
13.0809     2
12.9866     2
13.0078     2
13.0262     2
12.9473     2
12.9890     1
12.9251     1
12.8652     1
12.9621     1
12.9537     1
13.0496    

In [22]:
df_onlinefoods['longitude'].value_counts()

longitude
77.5773    36
77.6408    16
77.5533    14
77.6036    12
77.6221    11
77.6407    11
77.6529     9
77.6821     9
77.6044     8
77.6479     8
77.5923     8
77.5796     8
77.7500     8
77.5993     8
77.5713     7
77.5900     7
77.5284     7
77.5637     7
77.5390     7
77.5633     6
77.5434     6
77.6256     6
77.5821     6
77.6227     6
77.5921     6
77.5936     6
77.6593     6
77.5738     5
77.5764     5
77.6076     5
77.5931     5
77.5586     5
77.6848     5
77.5877     5
77.5741     5
77.6131     5
77.6399     4
77.5635     4
77.5464     4
77.5376     4
77.5995     4
77.7582     4
77.5658     4
77.6309     4
77.5491     4
77.6713     4
77.7081     4
77.6804     3
77.5400     3
77.6068     3
77.5565     2
77.4904     2
77.5864     2
77.5450     2
77.5691     2
77.5529     2
77.7132     2
77.6446     2
77.6200     2
77.5616     2
77.4921     2
77.5486     2
77.5577     2
77.6047     2
77.4842     2
77.6176     1
77.5332     1
77.4992     1
77.4941     1
77.5135     1
77.5240   

In [23]:
df_onlinefoods['Pin code'].value_counts()

Pin code
560009    36
560038    16
560010    14
560076    12
560034    11
560095    11
560036     9
560075     9
560029     8
560024     8
560001     8
560066     8
560043     8
560080     8
560015     7
560018     7
560011     7
560096     7
560003     7
560005     6
560017     6
560085     6
560027     6
560002     6
560021     6
560041     6
560008     6
560023     5
560092     5
560020     5
560006     5
560030     5
560103     5
560004     5
560042     5
560078     5
560070     4
560068     4
560048     4
560012     4
560046     4
560007     4
560014     4
560067     4
560100     4
560093     4
560022     3
560061     3
560025     3
560016     3
560028     2
560064     2
560062     2
560060     2
560056     2
560086     2
560102     2
560049     2
560013     2
560032     2
560097     2
560091     2
560055     2
560045     2
560019     2
560079     1
560059     1
560109     1
560104     1
560047     1
560073     1
560051     1
560026     1
560033     1
560050     1
560098     1
560

In [24]:
df_onlinefoods['Output'].value_counts()

Output
Yes    301
No      87
Name: count, dtype: int64

In [25]:
df_onlinefoods['Feedback'].value_counts()

Feedback
Positive     317
Negative      71
Name: count, dtype: int64

In [26]:
df_onlinefoods['Unnamed: 12'].value_counts()

Unnamed: 12
Yes    301
No      87
Name: count, dtype: int64

Printing out an unordered array of unique values in a Series, of each column composing the Dataset.

In [27]:
df_onlinefoods['Age'].unique()

array([20, 24, 22, 27, 23, 21, 28, 25, 32, 30, 31, 26, 18, 19, 33, 29])

In [28]:
df_onlinefoods['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [29]:
df_onlinefoods['Marital Status'].unique()

array(['Single', 'Married', 'Prefer not to say'], dtype=object)

In [30]:
df_onlinefoods['Occupation'].unique()

array(['Student', 'Employee', 'Self Employeed', 'House wife'],
      dtype=object)

In [31]:
df_onlinefoods['Monthly Income'].unique()

array(['No Income', 'Below Rs.10000', 'More than 50000', '10001 to 25000',
       '25001 to 50000'], dtype=object)

In [32]:
df_onlinefoods['Educational Qualifications'].unique()

array(['Post Graduate', 'Graduate', 'Ph.D', 'Uneducated', 'School'],
      dtype=object)

In [33]:
df_onlinefoods['Family size'].unique()

array([4, 3, 6, 2, 5, 1])

In [34]:
df_onlinefoods['latitude'].unique()

array([12.9766, 12.977 , 12.9551, 12.9473, 12.985 , 12.9299, 12.9828,
       12.9854, 12.8988, 12.9438, 12.8893, 12.9783, 12.982 , 13.0298,
       12.9983, 12.9925, 12.9306, 12.9353, 12.9155, 13.0019, 12.9698,
       12.9261, 12.9119, 12.9662, 12.9565, 13.0206, 12.9635, 13.0067,
       12.8845, 13.0158, 12.9343, 13.0012, 12.9442, 13.0487, 12.9889,
       12.9335, 13.102 , 12.9048, 12.9337, 12.9037, 13.0289, 12.9561,
       12.9579, 13.014 , 13.0138, 12.9537, 12.998 , 13.0496, 13.0166,
       13.0503, 12.9883, 13.0626, 12.957 , 12.8652, 12.9757, 12.9621,
       12.9217, 13.0223, 13.0262, 13.0078, 12.9105, 12.8834, 12.9149,
       12.9706, 13.0103, 13.0641, 12.9369, 13.0809, 12.9859, 12.9866,
       12.9847, 12.989 , 12.9251, 12.9967, 13.0734, 12.9515, 12.9719])

In [35]:
df_onlinefoods['longitude'].unique()

array([77.5993, 77.5773, 77.6593, 77.5616, 77.5533, 77.6848, 77.6131,
       77.7081, 77.5764, 77.5738, 77.6399, 77.6408, 77.6256, 77.6047,
       77.6409, 77.5633, 77.5434, 77.5585, 77.5135, 77.5713, 77.75  ,
       77.6221, 77.6446, 77.6068, 77.5484, 77.6479, 77.5821, 77.545 ,
       77.6036, 77.539 , 77.6044, 77.5995, 77.6076, 77.5923, 77.5741,
       77.5691, 77.5864, 77.6821, 77.59  , 77.5376, 77.54  , 77.5921,
       77.6309, 77.5658, 77.5877, 77.6176, 77.6227, 77.4941, 77.6804,
       77.5529, 77.5987, 77.5284, 77.5637, 77.524 , 77.5586, 77.5936,
       77.7132, 77.62  , 77.5577, 77.4842, 77.5486, 77.5635, 77.6529,
       77.5796, 77.5931, 77.6407, 77.5565, 77.6713, 77.4904, 77.5491,
       77.5332, 77.4992, 77.7582, 77.5464, 77.4921, 77.5128])

In [36]:
df_onlinefoods['Pin code'].unique()

array([560001, 560009, 560017, 560019, 560010, 560103, 560042, 560048,
       560078, 560004, 560068, 560038, 560008, 560032, 560033, 560021,
       560085, 560050, 560098, 560003, 560066, 560034, 560102, 560025,
       560026, 560043, 560002, 560086, 560076, 560096, 560029, 560046,
       560030, 560024, 560020, 560028, 560064, 560036, 560011, 560061,
       560022, 560027, 560007, 560012, 560006, 560047, 560005, 560073,
       560016, 560013, 560051, 560015, 560018, 560109, 560023, 560104,
       560041, 560049, 560045, 560055, 560060, 560062, 560070, 560075,
       560080, 560092, 560095, 560097, 560093, 560091, 560100, 560079,
       560059, 560067, 560014, 560056, 560072])

In [37]:
df_onlinefoods['Output'].unique()

array(['Yes', 'No'], dtype=object)

In [38]:
df_onlinefoods['Feedback'].unique()

array(['Positive', 'Negative '], dtype=object)

In [39]:
df_onlinefoods['Unnamed: 12'].unique()

array(['Yes', 'No'], dtype=object)

### <center>**DUPLICATES**</center>

In [40]:
# Checking duplicates.
duplicates = df_onlinefoods.duplicated().sum()
duplicates

103

### <center>**NULLS**</center>

In [41]:
# Checking nulls.
nulls = df_onlinefoods.isnull().sum()
nulls

Age                           0
Gender                        0
Marital Status                0
Occupation                    0
Monthly Income                0
Educational Qualifications    0
Family size                   0
latitude                      0
longitude                     0
Pin code                      0
Output                        0
Feedback                      0
Unnamed: 12                   0
dtype: int64

#### **<span style="color:#FFFF00">EDA Observations**</span>

**- Columns' names:** ['Age', 'Gender', 'Marital Status', 'Occupation', 'Monthly Income', 
       'Educational Qualifications', 'Family size', 'latitude', 'longitude',
       'Pin code', 'Output', 'Feedback', 'Unnamed: 12']

**- Numerical columns' names:** ['Age', 'Family size', 'latitude', 'longitude', 'Pin code']

**- Object columns' names:** ['Gender', 'Marital Status', 'Occupation', 'Monthly Income', 'Educational Qualifications', 'Output', 'Feedback', 'Unnamed: 12']

**- No nulls**

**- Types of data included in Dataset & number of columns containing that type:** float64(2), int64(3), object(8)

#### **<span style="color:#FFFF00">Transformation suggestions**</span>

- Column **['Unnamed: 12']** is unclear what type of information it contains, decision is for column to be dropped.

In [42]:
# Transformation to eliminate column ['Unnamed: 12'].

df_onlinefoods.drop(columns = 'Unnamed: 12', inplace=True)

- Column **['Monthly Income']** contains both text and numerical data, but the currency is unclear. Thus, it is decided we will change this to the internationally-known code INR, as well as include text for those two categories starting as a number.

(['No Income', 'Below Rs.10000', 'More than 50000', '10001 to 25000', '25001 to 50000'], dtype=object)

In [45]:
# Transformation to modify Rs. to the internationally-known code: INR

df_onlinefoods['Monthly Income'] = df_onlinefoods['Monthly Income'].replace({
    'No Income': 'No Income',
    'Below Rs.10000': 'Below 10000 INR',
    'More than 50000': 'More than 50000 INR',
    '10001 to 25000': 'Between 10001 and 25000 INR',
    '25001 to 50000': 'Between 25001 and 50000 INR'
})

- Column **['Output']** contains two types of values, which are object type. However, these should be boolean.

In [46]:
# Transformation to change the type of data from object to boolean.

df_onlinefoods['Output'] = df_onlinefoods['Output'].replace({'Yes': True, 'No': False})

-  Columns names are capitalized except for **['latitude']** and ['longitude'] and include a space between two strings of text. My suggestion would be to rename the columns so that they are all written in lowercase and spaces are replaced by a _.

In [48]:
# Transformation of columns' names by converting them to lowercase and replacing spaces with underscores.

def standardise_column_names(df):
    df.columns = [col.lower().replace(" ", "_") for col in df.columns]
    return df

#### **<span style="color:#FFFF00">Verification of applied changes**</span>

In [49]:
df_onlinefoods["monthly_income"].unique()

array(['No Income', 'Below 10000 INR', 'More than 50000 INR',
       'Between 10001 and 25000 INR', 'Between 25001 and 50000 INR'],
      dtype=object)

In [50]:
df_onlinefoods['output'].unique()

array([ True, False])

In [51]:
standardise_column_names(df_onlinefoods)

age  gender     marital_status      occupation  \
0     20  Female             Single         Student   
1     24  Female             Single         Student   
2     22    Male             Single         Student   
3     22  Female             Single         Student   
4     22    Male             Single         Student   
5     27  Female            Married        Employee   
6     22    Male             Single         Student   
7     24  Female             Single         Student   
8     23  Female             Single         Student   
9     23  Female             Single         Student   
10    22  Female             Single         Student   
11    23    Male             Single         Student   
12    23    Male             Single         Student   
13    21    Male             Single         Student   
14    23  Female             Single  Self Employeed   
15    24  Female             Single         Student   
16    28  Female             Single        Employee   
17    23  Female             Single         Student   
18    25    Male             Single         Student   
19    21  Female             Single         Student   
20    24    Male             Single         Student   
21    22    Male             Single         Student   
22    22  Female             Single         Student   
23    23    Male             Single         Student   
24    21    Male             Single         Student   
25    25    Male             Single         Student   
26    22  Female             Single         Student   
27    22    Male             Single         Student   
28    23  Female             Single        Employee   
29    22    Male             Single         Student   
30    22  Female             Single        Employee   
31    22    Male             Single         Student   
32    25    Male            Married        Employee   
33    22  Female             Single         Student   
34    22  Female             Single         Student   
35    25    Male             Single         Student   
36    25    Male             Single         Student   
37    32  Female  Prefer not to say      House wife   
38    23  Female             Single         Student   
39    23  Female             Single         Student   
40    30    Male            Married  Self Employeed   
41    23    Male             Single         Student   
42    23    Male             Single         Student   
43    22  Female             Single         Student   
44    22    Male             Single         Student   
45    27  Female            Married  Self Employeed   
46    24  Female             Single         Student   
47    23    Male             Single         Student   
48    23  Female             Single         Student   
49    22  Female             Single         Student   
50    23  Female             Single         Student   
51    23  Female             Single         Student   
52    24    Male             Single         Student   
53    25    Male             Single         Student   
54    22    Male             Single         Student   
55    28  Female            Married         Student   
56    22  Female             Single         Student   
57    24  Female             Single         Student   
58    31    Male            Married        Employee   
59    25    Male             Single         Student   
60    23    Male             Single         Student   
61    22    Male             Single         Student   
62    23    Male             Single         Student   
63    23    Male             Single         Student   
64    23  Female             Single         Student   
65    25    Male             Single         Student   
66    24    Male             Single        Employee   
67    23  Female             Single         Student   
68    23  Female             Single         Student   
69    24  Female            Married        Employee   
70    22    Male             Single         Student   
71    24  Female             Single         S

In [52]:
df_onlinefoods.head()

age  gender marital_status occupation   monthly_income  \
0   20  Female         Single    Student        No Income   
1   24  Female         Single    Student  Below 10000 INR   
2   22    Male         Single    Student  Below 10000 INR   
3   22  Female         Single    Student        No Income   
4   22    Male         Single    Student  Below 10000 INR   

  educational_qualifications  family_size  latitude  longitude  pin_code  \
0              Post Graduate            4   12.9766    77.5993    560001   
1                   Graduate            3   12.9770    77.5773    560009   
2              Post Graduate            3   12.9551    77.6593    560017   
3                   Graduate            6   12.9473    77.5616    560019   
4              Post Graduate            4   12.9850    77.5533    560010   

   output   feedback  
0    True   Positive  
1    True   Positive  
2    True  Negative   
3    True   Positive  
4    True   Positive

In [53]:
df_onlinefoods.tail()

age  gender marital_status occupation   monthly_income  \
383   23  Female         Single    Student        No Income   
384   23  Female         Single    Student        No Income   
385   22  Female         Single    Student        No Income   
386   23    Male         Single    Student  Below 10000 INR   
387   23    Male         Single    Student        No Income   

    educational_qualifications  family_size  latitude  longitude  pin_code  \
383              Post Graduate            2   12.9766    77.5993    560001   
384              Post Graduate            4   12.9854    77.7081    560048   
385              Post Graduate            5   12.9850    77.5533    560010   
386              Post Graduate            2   12.9770    77.5773    560009   
387              Post Graduate            5   12.8988    77.5764    560078   

     output  feedback  
383    True  Positive  
384    True  Positive  
385    True  Positive  
386    True  Positive  
387    True  Positive

In [54]:
df_onlinefoods.columns

Index(['age', 'gender', 'marital_status', 'occupation', 'monthly_income',
       'educational_qualifications', 'family_size', 'latitude', 'longitude',
       'pin_code', 'output', 'feedback'],
      dtype='object')

In [55]:
print(df_onlinefoods.dtypes)

age                             int64
gender                         object
marital_status                 object
occupation                     object
monthly_income                 object
educational_qualifications     object
family_size                     int64
latitude                      float64
longitude                     float64
pin_code                        int64
output                           bool
feedback                       object
dtype: object


### <center>**CSV DOCUMENT SAVING📁**</center>

In [56]:
# Saving the dataset to a csv file without an index.
df_onlinefoods.to_csv("onlinefoods_eda_completed.csv",index=False) # index=False prevents saving the row indices in the file